import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { resolve } from 'node:path';
const root = import.meta.dirname;
const read = name => readFileSync(resolve(root, name), 'utf8').replace(/\r\n?/g, '\n');
const patch = read('cordis.patch.yml');
const upstream = read('upstream-standard.patch.yml');
const pkg = JSON.parse(read('package.json'));
assert.equal(pkg.dsh.bundle.patch, './cordis.patch.yml');
assert.equal(pkg.peerDependencies, undefined);
assert.match(patch, /id: preset-grok-optimized/);
assert.match(patch, /id: grok-optimized/);
assert.doesNotMatch(patch, /dsh-tool-attachment-history|dsh-grok-work-state|agent-hub|dsh-upgrade|grokRequestBoundary/);
const withoutPersona = text => text.replace(/              prefix:[\s\S]*?(?=          - id: agent-instructions)/, '');
assert.equal(withoutPersona(patch.slice(patch.indexOf('        plugins:'))), withoutPersona(upstream.slice(upstream.indexOf('        plugins:'))), 'Non-persona behavior must equal the pinned official standard');
const persona = read('persona-prefix.md').trimEnd();
assert.ok(patch.includes(persona.split('\n').map(line => line ? '                ' + line : '').join('\n')), 'Installed persona must come from the maintained source');
const references = JSON.parse(read('reference-lock.json'));
assert.equal(references.host.version, '0.2.0-rc.2');
assert.equal(references.behavior.packageVersion, '1.0.45');
assert.match(references.behavior.commit, /^[a-f0-9]{40}$/);
assert.ok(pkg.files.includes('reference-lock.json'), 'Ship reviewed design provenance with the preset');
assert.doesNotMatch(read('persona-prefix.md'), /\bgrok-[A-Za-z0-9._-]+\b|openrouter|\bXAI_API_KEY\b/);
const generated = spawnSync(process.execPath, [resolve(root, '../../scripts/derive-grok-preset.mjs'), '--check'], { windowsHide: true, encoding: 'utf8' });
assert.equal(generated.status, 0, generated.stderr);
assert.equal(read('cordis.patch.yml'), patch, 'Preset generation must be deterministic');
console.log('PASS native preset bundle, official capability parity, dependency retirement and persona behavior');
